VERSION: 2
DATALOADER:
  ASPECT_RATIO_GROUPING: false
  FILTER_EMPTY_ANNOTATIONS: false
DATASETS:
  NAME: "channelIslandCT"
  DATA_ROOT: "/data/datasets/INTELLO/channelIslandCT"
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 2
  STEPS:
  - 5000
  - 15000
  - 30000
OUTPUT_DIR: "cnn_states/channelIslandCT"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 6
  REPLACE_BATCH_NORM: false
  PIXEL_MEAN:
  - 77.14670184158587
  - 80.10308534203995
  - 78.91256477749215
  PIXEL_STD:
  - 77.14670184158587
  - 80.10308534203995
  - 78.91256477749215
INPUT:
  NUM_INPUT_CHANNELS: 3
  NORMALISATION: 1
  IMAGE_SIZE: [224, 224]
AUGMENTATION:
  - NAME: "RandomBrightness"
    KWARGS:
      intensity_min: 0.8
      intensity_max: 1.2
  - NAME: "RandomContrast"
    KWARGS:
      intensity_min: 0.8
      intensity_max: 1.2
  - NAME: "RandomFlip"
    KWARGS:
      prob: 0.5
      horizontal: 1
      vertical: 0