VERSION: 2
DATALOADER:
  ASPECT_RATIO_GROUPING: false
  FILTER_EMPTY_ANNOTATIONS: false
DATASETS:
  NAME: "solar_panels_slope_aspect"
  DATA_ROOT: "/data/datasets/INTELLO/solarPanels/patches_800x600_slope_aspect_ir"
SOLVER:
  BASE_LR: 0.001
  IMS_PER_BATCH: 2
  STEPS:
  - 5000
  - 15000
  - 30000
OUTPUT_DIR: "cnn_states/solarPanels"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
  REPLACE_BATCH_NORM: false
  PIXEL_MEAN: [97.66963, 104.40458, 100.80986, 143.27992, 3.4355621, 112.70877, 0.7324577, 33.560642]
  PIXEL_STD: [36.103374, 31.923462, 30.820448, 32.04759, 9.596312, 17.102655, 6.382594, 48.46958]
INPUT:
  NUM_INPUT_CHANNELS: 8
  NORMALISATION: 1
  IMAGE_SIZE: [800, 600]
AUGMENTATION:
  - NAME: "RandomBrightness"
    KWARGS:
      intensity_min: 0.8
      intensity_max: 1.2
  - NAME: "RandomContrast"
    KWARGS:
      intensity_min: 0.8
      intensity_max: 1.2
  - NAME: "RandomFlip"
    KWARGS:
      prob: 0.5
      horizontal: 0
      vertical: 1
  - NAME: "RandomFlip"
    KWARGS:
      prob: 0.5
      horizontal: 1
      vertical: 0