_BASE_: base_solarPanels_pretrain.yaml
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 1
  STEPS:
  - 40000
  - 80000
  MAX_ITER: 200000
OUTPUT_DIR: "cnn_states/solarPanels/pretrain/frcnn_r50"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
  REPLACE_BATCH_NORM: False