VERSION: 2
DATALOADER:
  ASPECT_RATIO_GROUPING: false
  FILTER_EMPTY_ANNOTATIONS: false
DATASETS:
  NAME: "solar_panels"
  DATA_ROOT: "/data/datasets/INTELLO/solarPanels_rgb/patches_224x224"
SOLVER:
  BASE_LR: 0.001
  IMS_PER_BATCH: 2
  STEPS:
  - 5000
  - 15000
  - 30000
OUTPUT_DIR: "cnn_states/solarPanels/finetuned"
MODEL:
  WEIGHTS: "cnn_states/solarPanels/pretrain"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
  REPLACE_BATCH_NORM: false
  PIXEL_MEAN:
    - 125.100006
    - 129.38504
    - 119.02527
  PIXEL_STD:
    - 43.796257
    - 36.04708
    - 30.787947
INPUT:
  NUM_INPUT_CHANNELS: 3
  NORMALISATION: 1
  IMAGE_SIZE: [224, 224]
AUGMENTATION:
  - NAME: "RandomBrightness"
    KWARGS:
      intensity_min: 0.8
      intensity_max: 1.2
  - NAME: "RandomContrast"
    KWARGS:
      intensity_min: 0.8
      intensity_max: 1.2
  - NAME: "RandomFlip"
    KWARGS:
      prob: 0.5
      horizontal: 0
      vertical: 1
  - NAME: "RandomFlip"
    KWARGS:
      prob: 0.5
      horizontal: 1
      vertical: 0