_BASE_: base_solarPanels.yaml
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
  STEPS:
  - 80000
  MAX_ITER: 500000
OUTPUT_DIR: "cnn_states/solarPanels/frcnn_r50"
MODEL:
  META_ARCHITECTURE: "UNet"
INPUT:
  NUM_CLASSES: 2    # sem.seg. needs extra background class (0)